# Teleop configuration for Flysky RC controller
# Left thumb-stick up/down for velocity
# Right thumb-stick for steering
#
#    AXIS        Value
# Right Horiz.      0
# Right Vert.       1
# Left Horiz.     3
# Left Vert.      2


joy_teleop/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.1
    scale_linear_turbo:
      x: 1.5
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 1.2
    enable_button: 4
    enable_turbo_button: 5
    require_enable_button: True
#Below parameters are not required for flysky red dongle because joy_teleop/joy_node is not used as linear inputs are inverted but present anyways just for the sake of it.
joy_teleop/joy_node:
  ros__parameters:
    deadzone: 0.1
    autorepeat_rate: 100.0
    dev: /dev/input/flysky_red_js_port
